name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # We can leave this as empty. The value will be nil
  # But since the key is there, Github treats this as configured.
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    # Node 12.18 doesn't work with the elixir install
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: localhost
          POSTGRES_USER: postgres
          POSTGRES_DB: phoenix_blog_test
        # Set health checks to wait until postgres has started
        # >- ==> starting on new line after dash. Any new lines is
        # concatenated as a single line.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.10.3' # Define the elixir version [required]
          otp-version: '22.3' # Define the OTP version [required]
      - run: mix deps.get
      - run: mix deps.compile
      - run: cd assets && yarn install --frozen-lockfile
      - run: mix test
